/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApiSchoolpayRouteImport } from './routes/api-schoolpay'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSchoolpayRouteImport } from './routes/admin.schoolpay'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminHrRouteImport } from './routes/admin.hr'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as ApiPublicSchoolpayWebhookRouteImport } from './routes/api/public/schoolpay-webhook'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchoolpayRoute = ApiSchoolpayRouteImport.update({
  id: '/api-schoolpay',
  path: '/api-schoolpay',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchoolpayRoute = AdminSchoolpayRouteImport.update({
  id: '/schoolpay',
  path: '/schoolpay',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrRoute = AdminHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSchoolpayWebhookRoute =
  ApiPublicSchoolpayWebhookRouteImport.update({
    id: '/api/public/schoolpay-webhook',
    path: '/api/public/schoolpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-schoolpay': typeof ApiSchoolpayRoute
  '/contact': typeof ContactRoute
  '/eligibility': typeof EligibilityRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/schoolpay': typeof AdminSchoolpayRoute
  '/api/public/schoolpay-webhook': typeof ApiPublicSchoolpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-schoolpay': typeof ApiSchoolpayRoute
  '/contact': typeof ContactRoute
  '/eligibility': typeof EligibilityRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/schoolpay': typeof AdminSchoolpayRoute
  '/api/public/schoolpay-webhook': typeof ApiPublicSchoolpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-schoolpay': typeof ApiSchoolpayRoute
  '/contact': typeof ContactRoute
  '/eligibility': typeof EligibilityRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/schoolpay': typeof AdminSchoolpayRoute
  '/api/public/schoolpay-webhook': typeof ApiPublicSchoolpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-schoolpay'
    | '/contact'
    | '/eligibility'
    | '/login'
    | '/partners'
    | '/portal'
    | '/projects'
    | '/services'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/cms'
    | '/admin/hr'
    | '/admin/projects'
    | '/admin/schoolpay'
    | '/api/public/schoolpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api-schoolpay'
    | '/contact'
    | '/eligibility'
    | '/login'
    | '/partners'
    | '/portal'
    | '/projects'
    | '/services'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/cms'
    | '/admin/hr'
    | '/admin/projects'
    | '/admin/schoolpay'
    | '/api/public/schoolpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-schoolpay'
    | '/contact'
    | '/eligibility'
    | '/login'
    | '/partners'
    | '/portal'
    | '/projects'
    | '/services'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/cms'
    | '/admin/hr'
    | '/admin/projects'
    | '/admin/schoolpay'
    | '/api/public/schoolpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiSchoolpayRoute: typeof ApiSchoolpayRoute
  ContactRoute: typeof ContactRoute
  EligibilityRoute: typeof EligibilityRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  PortalRoute: typeof PortalRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  ApiPublicSchoolpayWebhookRoute: typeof ApiPublicSchoolpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-schoolpay': {
      id: '/api-schoolpay'
      path: '/api-schoolpay'
      fullPath: '/api-schoolpay'
      preLoaderRoute: typeof ApiSchoolpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schoolpay': {
      id: '/admin/schoolpay'
      path: '/schoolpay'
      fullPath: '/admin/schoolpay'
      preLoaderRoute: typeof AdminSchoolpayRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr': {
      id: '/admin/hr'
      path: '/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AdminHrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/schoolpay-webhook': {
      id: '/api/public/schoolpay-webhook'
      path: '/api/public/schoolpay-webhook'
      fullPath: '/api/public/schoolpay-webhook'
      preLoaderRoute: typeof ApiPublicSchoolpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminHrRoute: typeof AdminHrRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSchoolpayRoute: typeof AdminSchoolpayRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminHrRoute: AdminHrRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSchoolpayRoute: AdminSchoolpayRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiSchoolpayRoute: ApiSchoolpayRoute,
  ContactRoute: ContactRoute,
  EligibilityRoute: EligibilityRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  PortalRoute: PortalRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  ApiPublicSchoolpayWebhookRoute: ApiPublicSchoolpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
